## Video
profile=high-quality

## Behavior (personal preference)
keep-open=yes
image-display-duration=inf
save-position-on-quit

## Screenshots
screenshot-format=png
screenshot-dir="~/Pictures/mpv"
screenshot-template="%F-%p-%n"
screenshot-high-bit-depth=no

## Language Priority
slang=eng,en
alang=jpn,ja

## HW Decoding
hwdec

## Looping
loop-playlist=inf
loop-file=inf

## Subtitles
sub-auto=fuzzy
sub-file-paths=Subs:subs:subtitles:ENG Subs
sub-fonts-dir=fonts

## OSD (requires uosd)
osd-bar=no

