import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 10.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 100000

[window]
decorations = "None"
dynamic_title = true
opacity = 0.9
startup_mode = "Maximized"

[window.dimensions]
columns = 132
lines = 43

[window.padding]
x = 16
y = 8
